# Generated by Django 5.0.3 on 2024-05-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('rua', models.CharField(max_length=150)),
                ('numero', models.IntegerField()),
                ('cidade', models.CharField(max_length=120)),
                ('uf', models.CharField(max_length=60)),
                ('cep', models.CharField(max_length=20)),
                ('bairro', models.CharField(max_length=120)),
            ],
        ),
    ]
